version: '3'
services:
  cities-generator-service.vige.it:
    image: "vige/cities-generator:1.1.9"
    ports:
      - "8380:8080"
    environment:
      - REALM=vota-domain
      - AUTHURL=http://vota-auth.vige.it:8480/auth
      - RESOURCE=citiesGenerator
      - COUNTRY=${COUNTRY}
  vota-auth.vige.it:
    image: "vige/vota-auth:1.0.0"
    ports:
      - "8480:8480"
  vota-votingpapers.vige.it:
    image: "vige/vota-votingpapers:1.0.0"
    ports:
      - "8180:8180"
  vota-voting.vige.it:
    image: "vige/vota-voting:1.0.0"
    ports:
      - "8080:8080"
  vota-history.vige.it:
    image: "vige/vota-history:1.0.0"
    ports:
      - "8280:8280"