version: '3'
services:
  citiesgenerator:
    image: "vige/cities-generator"
    ports:
      - "8743:8443"
    environment:
      - COUNTRY=${COUNTRY}
  auth:
    image: "vige/vota-auth"
    ports:
      - "8843:8843"
    environment:
      - VOTINGPAPERS_URL=https://vota-votingpapers.vige.it:8543
      - VOTING_URL=https://vota-voting.vige.it:8443
      - HISTORY_URL=https://vota-history.vige.it:8643
  votingpapers:
    image: "vige/vota-votingpapers"
    ports:
      - "8543:8543"
  voting:
    image: "vige/vota-voting"
    ports:
      - "8443:8443"
  history:
    image: "vige/vota-history"
    ports:
      - "8643:8643"