version: '3'
services:
  citiesgenerator:
    image: "vige/cities-generator"
    ports:
      - "8743:8443"
    environment:
      - COUNTRY=${COUNTRY}
  votingpapers:
    image: "vige/vota-votingpapers"
    ports:
      - "8543:8543"
  voting:
    image: "vige/vota-voting"
    ports:
      - "8443:8443"
  history:
    image: "vige/vota-history"
    ports:
      - "8643:8643"