version: '3'
services:
  votingpaper:
    image: "vige/vota-votingpaper"
    ports:
      - "8543:8543"
  backend:
    image: "vige/vota-backend"
    ports:
      - "8443:8443"
  frontend:
    image: "vige/vota-frontend"
    ports:
      - "443:443"
  report:
    image: "vige/vota-report"
    ports:
      - "8643:443"