version: '3'
services:
  citiesgenerator:
    image: "vige/cities-generator"
    ports:
      - "8743:8443"
    environment:
      - REALM=vota-domain
      - AUTHURL=https://vota-auth.vige.it:8843/auth
      - RESOURCE=citiesGenerator
      - COUNTRY=${COUNTRY}
  auth:
    image: "vige/vota-auth"
    ports:
      - "8843:8843"
  votingpapers:
    image: "vige/vota-votingpapers"
    ports:
      - "8543:8543"
  voting:
    image: "vige/vota-voting"
    ports:
      - "8443:8443"
  history:
    image: "vige/vota-history"
    ports:
      - "8643:8643"