version: '3'
services:
  votingpapers:
    image: "vige/vota-votingpapers"
    ports:
      - "8543:8543"
  voting:
    image: "vige/vota-voting"
    ports:
      - "8443:8443"
  history:
    image: "vige/vota-history"
    ports:
      - "8643:8643"
  frontend:
    image: "vige/vota-frontend"
    ports:
      - "443:443"
  report:
    image: "vige/vota-report"
    ports:
      - "543:443"